# Site settings
title: polomski
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Marcin Połomski
description: "Marcin Połomski GitHub Page | MarcinPolomski | polomski"
baseurl: "https://polomski.github.io"
url: "https://polomski.github.io"
#twitter_username: MarcinPolomski
github_username:  polomski

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

gems: [jekyll-paginate, jekyll-feed]
